#:kivy 2.3.1
#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import dp kivy.metrics.dp

<LoginScreen>:
    name: "login"
    MDBoxLayout:
        orientation: "horizontal"

        FitImage:
            source: "assets/login_image.png"
            size_hint_x: 0.5

        MDBoxLayout:
            orientation: "vertical"
            padding: [dp(50), dp(50), dp(50), dp(50)]
            spacing: dp(20)
            size_hint_x: 0.5
            md_bg_color: get_color_from_hex("#F5F6FA")

            FitImage:
                source: "assets/logo.png"
                size_hint: None, None
                size: dp(100), dp(100)  
                pos_hint: {"center_x": 0.5}

            MDLabel:
                text: "Connexion à K'iosk"
                font_size: "24sp"
                size_hint_y: None
                halign: "center"
                height: self.texture_size[1]

            MDTextField:
                id: email_input

                MDTextFieldHintText:
                    text: "Email"

            MDTextField:
                id: mdp_input
                password: True

                MDTextFieldHintText:
                    text: "Mot de Passe"

            MDGridLayout:
                cols: 2
                spacing: dp(30)
                size_hint: None, None
                size: self.minimum_size
                pos_hint: {"center_x": 0.5}  
                padding: 0

                MDButton:
                    style: "elevated"
                    on_release: root.se_connecter()

                    MDButtonIcon:
                        icon: "login"
                                
                    MDButtonText:
                        text: " Se connecter "      

                MDButton:
                    style: "elevated"

                    on_release:
                        root.manager.current = "register"

                    MDButtonText:
                        text: "Créer un compte"

                    MDButtonIcon:
                        icon: "account-plus"
            Widget:
                size_hint_y: 0.2