#:kivy 2.3.1
#:import dp kivy.metrics.dp
#:import get_color_from_hex kivy.utils.get_color_from_hex

<StockScreen>:
    name: "stock"
    MDBoxLayout:
        orientation: "vertical"
        padding: [dp(24), dp(24), dp(24), dp(24)]
        spacing: dp(20)
        md_bg_color: get_color_from_hex("#F5F6FA")

        BoxLayout:
            orientation: "horizontal"
            size_hint_y: None
            height: dp(48)
            MDButton:
                style: "filled"
                on_release: root.manager.current = "home"
                MDButtonText:
                    text: "Retour à l'accueil"
                    
                MDButtonIcon:
                    icon: "arrow-left"

        MDLabel:
            text: "Gestion du Stock"
            font_size: "32sp"
            bold: True
            halign: "center"
            theme_text_color: "Primary"
            size_hint_y: None
            height: dp(60)

        MDTextField:
            id: filtre_input
            hint_text: "Filtrer par nom ou stock..."
            on_text: root.filtrer(self.text)
            size_hint_y: None
            height: dp(48)
            mode: "outlined"
            icon_left: "magnify"

        BoxLayout:
            orientation: "vertical"
            size_hint_y: 1
            ScrollView:
                MDList:
                    id: stock_list
            Widget:
                size_hint_y: None
                height: dp(8)